apiVersion: v1
kind: Service
metadata:
  name: httpd-k8s-service
spec:
  type: LoadBalancer
  selector:
    role: httpd-k8s
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-k8s-deployment
  labels:
    role: httpd-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      role: httpd-k8s
      tier: web
  template:
    metadata:
      labels:
        role: httpd-k8s
        tier: web
    spec:
      containers:
      - name: httpd-k8s-app
        image: iad.ocir.io/idtu5rnw5dhj/httpd-k8s:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ocirsecret